# Generated by Django 5.1.4 on 2025-02-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portofolio",
            name="image",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to=""
            ),
        ),
    ]
