# Generated by Django 5.1.4 on 2025-02-16 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio", "0007_portofolio_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pengalamankerja",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pengalamankerja",
            name="user",
            field=models.ForeignKey(
                max_length=20,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portofolio",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
