# Generated by Django 5.1.4 on 2025-02-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio", "0009_certificate_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="KindSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_category", models.CharField(max_length=100)),
            ],
        ),
    ]
