# Generated by Django 5.1.4 on 2025-02-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio", "0011_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="pengalamankerja",
            name="image",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="image/"
            ),
        ),
    ]
