# Generated by Django 5.1.4 on 2025-02-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bio", "0013_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
